apiVersion: apps/v1
kind: Deployment
metadata:
  name: vertex-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vertex-api
  template:
    metadata:
      labels:
        app: vertex-api
    spec:
      containers:
      - name: vertex-api
        image: vertex-api:latest
        ports:
        - containerPort: 8000