apiVersion: apps/v1
kind: Deployment
metadata:
  name: vert-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vert-api
  template:
    metadata:
      labels:
        app: vert-api
    spec:
      containers:
      - name: vert-api
        image: vert-api:latest
        ports:
        - containerPort: 8000
